### ISSUE TITLE
Y axis range 

### ISSUE THREAD

**Issue by ZmG** [Brunel-Visualization/Brunel#104]
I have the following visualization:
![screen shot 2016-06-02 at 4 20 10 pm](https://cloud.githubusercontent.com/assets/4634239/15760725/8aa0463c-28e2-11e6-9677-e78f8d5349c2.png)

My problem is that the y-axis starts at -1 while I would have expect it to start at 0. Is there a way to manually specify what value is your x or y axis starting at?

Going through the documentation I spotted the yrange  and I thought it would solve my issue but I got the following exception when including yrange: _Unknown field #series_ 

This is reproducible in the Brunel renderer(http://brunel.mybluemix.net/gallery_app/renderer):
`data('ab4d76d2-2748-4287-bf6d-b4a30a0f8bfa')  title("Top 5 Countries with highest precipitation") x(Year) y(Colombia,China,Venezuela,India,Chile) color(#series) axes(x:'Years',y:'Precipitation (million cubic meters)')tooltip('Value for ',#series, ' is ',#values) + line x(Year) y(Colombia,China,Venezuela,India,Chile) color(#series) `

**Comment by grahamwills** [comment]
'yrange' is used instead of 'y' to make an element that spans a range of values -- it's not actually affecting the range. For this chart we have two plans:

[1] It shouldn't default to below zero -- we'll consider that a defect and fix it
[2] We will add syntax to allow a field to have a defined min and max range to display it over

This will be added to develop, and appear in the 2.0 milestone release

**Comment by danrope** [comment]
On develop, this graph defaults below 0 on Y.  Unsure if the fix for this [1] above is part of this.

`data('https://gist.githubusercontent.com/suntong/416bcaa0ae3156c5a15cbcc7018344d1/raw/6fd49a1be8ce7278bd7fcd411c3300c42cbbd0f5/HeatMap.csv') x(DOW) y(Hour) color(changes:[white, purple]) label(changes) tooltip(#all) mean(changes) style('symbol:rect; size:100%;) stroke:none')`
