### ISSUE TITLE
Tooltip persists after leaving point

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#126]
Create a chart with a tooltip.  Hover over the item with the tooltip and you will see the tooltip.  Now stop hovering (move mouse away).  Sometimes the tooltip persists, and won't go away.

**Comment by grahamwills** [comment]
I believe this was caused because multiple event handlers were competing for the same events. I have modified the code to give each event a type. I replicated the defect when using both tooltip and interaction(select) and verified the fix solved the issue, so hopefully all will be well in the upcoming  build.
