### ISSUE TITLE
Restrict Pan and Zoom to not pan/zoom to empty chart

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#128]
Currently, you can pan and/or zoom all of the chart elements out of view so that what you end up with is an empty chart. Please restrict pan and zoom so that this does not occur.

**Comment by grahamwills** [comment]
It is not easy to implement this feature completely as, for example, with a scatterplot we would need to know where each point lies to allow pan and zoom, and that would be very compute intensive. 

However we have implemented a feature that

  * Restricts that maximum in/out zoom to a factor of 3 for coordinate charts
  * Disallows panning and zooming which would have 50% of either dimension (x or y) not allocated to the data space

This means that if your data fill the data space, you would always see at least half of the display space in both dimensions with data. However if your data points are not evenly distributed,there could easily be an empty screen because we display data space without checking if points are actually in that space.

In practice, it is a significant improvement and if you do pan outside the range, it is relatively easy to get back to a reasonable solution.
