### ISSUE TITLE
Collapsable trees (enhancement)

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#141]
Add a capability to visualize trees with dynamic behavior: collapsing and expanding nodes to support large trees. Probably a syntax very similar to tree maps may work. If a tree is large, the initial state needs to be collapsed: e.g. the configuration may include the number of initially expanded layers - the rest of items would be in collapsed state and user would need to expand them to explore the tree. Some additional options may be of interest: 
- the size/color of nodes and links (they may match to tree node attributes);
- the orientation (or topology) of tree growth.

**Comment by grahamwills** [comment]
We've been working on trees for a little bit -- they ALMOST made 2.0, but not quite, so I strongly expect them to make a version in a few months. Some code for them is in the system, but is not advertised yet -- because it's fragile and not fully built. 

You can try out the prototype feature which currently only works if you specify a single x and a single y field. The syntax SHOULD indeed work exactly like tree maps -- just change "treemap" to "tree" and all should be good. Currently though, I think it';s getting confused and trying to build odd scales if you try any more than one x or y field.

Anyway, for a preview of the current state, try this basic syntax:

`data('sample:US States.csv') tree x(region) y(boys_name) label(abbr) color(presidential_choice)`

You can using aggregation and the usual data functions to modify this:

`data('sample:US States.csv') tree x(region) y(boys_name) label(abbr) color(presidential_choice) size(#count:200%) list(abbr) sort(#count)`

and we allow either `transpose` or `polar` to be added to change the layout:

`data('sample:US States.csv') tree x(region) y(boys_name) label(abbr) color(presidential_choice) transpose`

`data('sample:US States.csv') tree x(region) y(boys_name) label(abbr) color(presidential_choice) polar`

In terms of the basic look, are these close to what you expect? I'll add another comment on interactivity to talk more about that

**Comment by grahamwills** [comment]
## Tree interactivity -- especially for large trees

Currently pan and zoom work (and are on by default). These are not purely graphical, so as you zoom in more detail can be seen, not just everything scaled up. For trees, however, we really do want some interactivity specific to the hierarchy. This should also apply to `treemap` and `bubble` diagrams (but may be off by default for them, as it might be less useful)

Here's a few thoughts as to what we might do:

`interactivity(collapse)` could be a basic use -- that would enable handlers for collapsing nodes. We'd give the collapsed node a css style tag so it would, by default, look different, and users could modify it to look as they desired. The default would also be using a click, but we could add an event name (as we do for select). mouseover would be horrible, but I can see only doing it for double-clicks as an option.

The suggestion of automatically collapsing for large trees is a very appealing one! It might be a parameter in the tree diagram command, in which case we might allow a number to specify the maximum number of nodes to show (the default might be calculated based on screen size -- maybe to show no more than a given number of nodes per square inch)

For automatic pruning, any algorithm descriptions or suggestions people have would be great. I'd probably do something like this as an ad-hoc algorithm: 
- for each interior node, calculate the descendant sizes that would be hidden by collapsing it
- discount that by a function of the distance from the root (so things further out get hidden sooner)
- repeatedly collapse until we are under the desired number of nodes  

-

**Comment by ap-aep** [comment]
Thank you very much for the details about the tree visualization implementation! I used it successfully to build a tree from my data and the outcome looks nice. I am looking forward to try the tree's/tree map's interactive behavior when a prototype is available. Thank you again!

**Comment by grahamwills** [comment]
Will be in the next release version and also in the branch master2.1
