### ISSUE TITLE
Labels collide with chart when positioned outside, left

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#155]
I have a bar chart where I am putting the labels outside and to the left of the bars.
When I zoom in, if the label overlaps the adjacent bar, it doesn't get hidden.  If I remove the "-left" portion, it seems to work better.  It would be nice if the labels only showed when they weren't on top of an adjoining bar.

Here is a sample syntax I'm using.
data('sample:US States.csv') bar x(abbr) sort(population) y(population) interaction(panzoom:x) label(abbr) style('.label {label-location:outside-top-left;}')

**Comment by grahamwills** [comment]
This is by design. A label that is outside does not get hidden except if it overlaps other labels.
However, placing a label outside-top-left will have the END of the text aligned with the top-left of the bar -- it might be better to add text-align:start also as a style so it is drawn STARTING from that point and therefor over the top of the bar:

`data('sample:US States.csv') bar x(abbr) y(population) sort(population) label(abbr) style('.label {label-location:outside-top-left; text-align:start;}') interaction(pan zoom:x)`
