### ISSUE TITLE
Plotting data points on a State specific map

### ISSUE THREAD

**Issue by sourav-mazumder** [Brunel-Visualization/Brunel#161]
Hi,

Need to plot data points overlayed on a State specific map. I don't want to map the points on the big USA map as in that case my points would be all concentrated in a very small area,

Is there a way to achieve it ? I could do the same in R using shape file specific to the State.

Regards,
Sourav

**Comment by danrope** [comment]
Try supplying the state name in the `map` action:

`
data('sample:US States.csv') map("michigan")`

**Comment by sourav-mazumder** [comment]
@danrope 

Hi Dan,

Thanks for your reply. 

But this does not work either.  It still shows the entire map of the US.

Is the dataset needs to have a coloumn 'state' with value as say '"michigan" ?

Regards,
Sourav

**Comment by grahamwills** [comment]
Currently our logic does not "zoom in" beyond the map file level, so the lowest level for "michigan" is (in my examples) the states around it. I'm adding an "enhancement" labels because we could do this and I agree it is useful.

Another possibility would be to specifically request a lat/long bounding box, like this: 

 `map("usa") + data('sample:US States.csv') y(latitude:[42,48]) x(longitude:[-90,-82])`

This should at least zoom into that area. Unfortunately that doesn't work at the moment -- the generic `map("usa")` decides it really should fill the space. I think I'd just consider that a defect, although the current behavior is defensible.

Would that be an OK solution, or is it better to wait for a bit and implement the enhancement?

**Comment by sourav-mazumder** [comment]
@grahamwills 

Zooming in using the lat/long should work also as a stop gap. But will it be possible to fix the defect you have mentioned ?

Regards,
Sourav

**Comment by grahamwills** [comment]
Adding this as a defect; when fix, you will be able to specify the x and y ranges as given above to create the initial zoom for the map

**Comment by grahamwills** [comment]
validated in 2.2, to be released very shortly
