### ISSUE TITLE
String function "contains" is not supported in IE/Edge

### ISSUE THREAD

**Issue by PhilHall-IBM** [Brunel-Visualization/Brunel#168]
There are a number of instances in the Brunel js files where the string function 'contains' is used - this is not supported on IE/Edge (see image for error).

In most cases, the 

`s.contains("findme")`

Can be simply be replaced with:

`s.search("findme") > -1`

![b92358959050e6](https://cloud.githubusercontent.com/assets/11235667/19120394/a6c1535e-8af0-11e6-8697-5b0aaf71d87a.png)

**Comment by grahamwills** [comment]
Well,s sadly, the fix is not that easy. I don't have edge or IE 11, so Ic cannot test it out, but documentation (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/1173756/) indicates that IE11 and (maybe) Edge has a defect that they do not support the classList property of SVG DOM items. This means that the code seeing if the class list contained a certain value was failing.

I added a workaround/fix to the code that simply ignores that check -- it likely means that SVG elements are not given the class "selected" when they are selected, but at least the rest of selection will work.

**Comment by grahamwills** [comment]
Oh, I should add that the fix is on the "select" branch and will move to master at the end of the Milestone, Jan 6
