### ISSUE TITLE
filter slider does not work --- many exceptions

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#192]
When you move the handle of the slider, nothing happened to the chart. There are so many exceptions displayed in the console window.
![image](https://cloud.githubusercontent.com/assets/21226717/22040073/38d665f4-dcc7-11e6-831d-de783682bc3e.png)

I'm attaching my html file here to show the problem.

[filter_slider.zip](https://github.com/Brunel-Visualization/Brunel/files/712332/filter_slider.zip)

**Comment by grahamwills** [comment]
I believe the errors were being caused by Brunel trying to create a tooltip for a circle that had been hidden. I added a guard for it an it seems to work, at least for the following Brunel:

`data('sample:LesMis-Characters.csv') x(Main) y(ID) key(ID) filter(Main) tooltip(#all) + data('sample:LesMis-Connections.csv') edge color(Count) key(A, B) tooltip(#all)`
