### ISSUE TITLE
Issues with visualizing word clouds if multiple items are selected on the primary graph

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#219]
For a dashboard composed from 2 related charts:
%%brunel data('topicsContent') bar x(topic) y(weight) color(weight) sort(weight) sum(weight) tooltip(#all) interaction(select) | 
interaction(filter)  cloud color(weight) size(weight) sort(weight) label(word)  
:: width=800, height=500

While using shift to choose multiple topics on the primary chart, Brunel shows an incorrect  word cloud visualization - the words of the second cloud are visualized as very small in comparison with the words of the first cloud.

**Comment by grahamwills** [comment]
There was a defect in repeated calls to the word cloud routine; this has been fixed in the latest branch (2.4).  For this chart, I suggest adding a ".selected" css style for the first one so you can tell which bars have been selected:

`bar x(topic) y(weight) color(weight) sort(weight) tooltip(#all) sum(weight) style('.selected {stroke:red; stroke-width:2px; stroke-opacity:1}') interaction(select) | cloud color(weight) size(weight) sort(weight) label(word) interaction(filter)`
