### ISSUE TITLE
Setting style affects the legend while defined for visualization

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#220]
Example:
%%brunel data('countsDataframe') cloud color(occurrence) size(occurrence) sort(occurrence)   label(word) style(':nth-child(odd) { font-family:Impact;font-style:normal') style(':nth-child(even) { font-family:Times; font-style:italic;font-size:200px') tooltip(#all) 
:: width=800, height=500

In this example, the labels for legend become so large that overlap with the visualization.
Current workaround is to use legends(none)

**Comment by grahamwills** [comment]
The issue is that the styles specified affect everything in the chart -- the solution is to limit them only to the element items; the easiest way of doing that is to add the `element` class to the style, like this:

`style('**.element**:nth-child(odd) { font-family:Impact;font-style:normal')`

this limits the effect to items classed as elements, which are the main data items, not the legends. I tested this on the US states data set using the following syntax:

`text cloud x(Girls_Name) color(Girls_Name) size(#count) style('.element:nth-child(odd) { font-family:Impact;font-style:normal') style('.element:nth-child(even) { font-family:Times; font-style:italic;font-size:200px')`
