### ISSUE TITLE
Brunel 2.4: issues with colors of map items with minimum values

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#231]
I used the US map  (states level) colored with range of "reds" colors based on value having non-negative reals.  The items with the actual value 0 (min possible value in my case) are shown in blue instead of the lowest possible color.   The states with absent info are shown in grey as it should be.

**Comment by grahamwills** [comment]
Ah, the perils of writing in multiple languages simultaneously. I used a Javascript shortcut to check for a null or undefined value, ignoring the fact that zero is also not truthy, and we didn't have a good check for that in our tests. The fix was in the Java generation code and I have posted a new version online.
