### ISSUE TITLE
Tree root node often clipped

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#235]
You can replicate the problem with any data. Here is the data and syntax you can use to see the problem.

data file: SyntheticTree.csv
syntax: edge size(LinkStrength:[100%, 600%]) key(Parent, ID) label(Parent, '/', ID) style('symbol:curved') + tree color(type:[#a00000, yellow]) size(nodeSize:[200%, 150%]) key(ID)"

Here is screen shot tree root node which is clipped:

![tree_root_node_cliped](https://user-images.githubusercontent.com/21226717/26994420-34b9532e-4d2d-11e7-954f-d14b0de7c033.jpg)

Please get data file and the Brunel .html from the zip.

[BrunelTestApp.zip](https://github.com/Brunel-Visualization/Brunel/files/1065242/BrunelTestApp.zip)

**Comment by grahamwills** [comment]
There may be a remaining issue with #count when using the induced tree; because the maximum value for that is on an internal calculated node, not on a "real" node with data, but that is not the case for this example -- and it's really a bit of a pathological case (I'm tempted to just hide the root for that case anyway) so I'm happy with the fix for just this more normal case
