### ISSUE TITLE
Support for languages with bidirectional scripts (i.e. Arabic / Hebrew) 

### ISSUE THREAD

**Issue by tomerm** [Brunel-Visualization/Brunel#236]
Publishing draft version of design document providing:
1. Essential information on basic Bidi requirements
2. End user perspective for suggested enhancements to Brunel
3. Insights into the implementation of each of Bidi requirements inside Brunel.

[Brunel_BidiSDD0_18June2017.pdf](https://github.com/Brunel-Visualization/Brunel/files/1083154/Brunel_BidiSDD0_18June2017.pdf)

@grahamwills and  @danrope please have a look and share your feedback. I would like to finalize the overall approach before submitting PRs with implementation. Many thanks in advance.

**Comment by tomerm** [comment]
[Brunel_BidiSDD0_26June2017.pdf](https://github.com/Brunel-Visualization/Brunel/files/1102654/Brunel_BidiSDD0_26June2017.pdf)
Uploading an updated version of design document providing more lower lever design details. This is considered the final version of the design document. It must be reviewed/approved first before we submit actual implementation via separate PR.

**Comment by grahamwills** [comment]
This proposed change has been reviewed and is ACCEPTED. I will be happy to integrated the changes as proposed, with minor syntax changes as suggested below. If you have concern over the proposed syntax modifications, let me know -- this is not a critical issue.

------------------------------------------------------------

# Review of "Bidi support in Brunel; Functional specification document SDD0"

### GUI flipping / Mirroring

Brunel's online GUI application is only a demo and is both weakly supported and little used. I would consider it out of scope. Our main non-chart widgets are the filter controls

### 1.4.2

> we leverage as much as possible D3 support

Excellent, we want to keep doing so to make upgrading with the latests versions of D3 as easy as possible and leverage D3's huge community of users and hence testers.

### 2.1.1 Icons mirroring

Brunel uses icons for point symbols in charts only. These are mostly non-directional, and the directional ones must be manually requested by the end user (and so can be reversed as required)

### 2.2.1 Locale specification

> A new property called locale is defined to pass locale information to Brunel

A slight modification here. For future expansion, I'd prefer to use a more generic property with keyword usage. So instead of:

	bar x(age) y(#count) sort(#count) tooltip (#all) locale(he)
	
etc, I would prefer:
	
	bar x(age) y(#count) sort(#count) tooltip (#all) output(locale:he)
	
	bar x(age) y(#count) sort(#count) tooltip (#all) output(guidedir:rtl)

and so on. This is simply a syntactical difference; I do not believe it influences any of the semantics in the rest of the document.

> If locale is not explicitly specified, browser local (default browser language) is used

For the plan as described by this document, this will not be possible. The code for the chart is partially created by the Java component, which is not guaranteed to be using the same locale as the Browser. Thus Brunel itself cannot guarantee that we will be using the browser locale consistently. **However this is unlikely to be an issue in practice**, as application browser code (e.g. within a notebook) can easily add the locale to the Brunel code to guarantee this property.

So, my suggestion is that we assume that any application will construct or append a default locale information to any existing Brunel to ensure that a locale is always specified. This will be relatively easy in the Python, R and Scala drivers for notebooks, for example.


### 2.3 Functional specification

`brunel-tokens.txt` needs slightly different modification for the new syntax, but otherwise this looks good. I might make minor modifications afterwards (e.g. making `ltr` and `rtl` enumerated types) but those are purely internal code polishing steps, not necessary ones.


### 3.2 End user perspective

As per the previous section, I would prefer to use a single `output` command and place the `numshape` and `textdir` properties inside it as options to use.

### 3.3 Functional specification

The proposed specifications look fundamentally good to me. It is likely I will make changes after adoption to adapt to the Brunel code "look and feel" (e.g. changing `BrunelLocale` to `formatLocale` or similar), but those are minor details.


------------------------------------------------------------


[review of bidi brunel support proposal.pdf](https://github.com/Brunel-Visualization/Brunel/files/1103260/review.of.bidi.brunel.support.proposal.pdf)

[review of bidi brunel support proposal.txt](https://github.com/Brunel-Visualization/Brunel/files/1103263/review.of.bidi.brunel.support.proposal.txt)

**Comment by tomerm** [comment]
@grahamwills thanks a lot for the swift review and invaluable comments. 
Can you please clarify the expected syntax in case we wish to specify several parameters. Should it be as follows:
`bar x(age) y(#count) sort(#count) tooltip (#all) output(guidedir:rtl,locale:he,textdir:auto)`

@GBR-613 once you submit the PR please connect it to this issue so that we can close it. Thx.

**Comment by grahamwills** [comment]
Yes, this is the format. Brunel has very simple syntax, and this is the correct way to specify multiple parameters. in the tokens file, `guidedir`, `locale` and `textdir` would all be allowable options.

I believe the following definition in brunel-tokens.txt will work:

`output other + locale guidedir textdir numshape`

**Comment by GBR-613** [comment]
It looks like filter controls are a challenge and their Bidi support will not be included in the nearby pull request.  We will provide their support in a separate effort.

**Comment by GBR-613** [comment]
Pull request is created:  [https://github.com/Brunel-Visualization/Brunel/pull/238](https://github.com/Brunel-Visualization/Brunel/pull/238)

**Comment by tomerm** [comment]
Closing this issue since:

- design was reviewed / accepted and 
- code based on that design was submitted via #238 .

**Comment by tomerm** [comment]
@amirbrans FYI.
