### ISSUE TITLE
Improve Generation API

### ISSUE THREAD

**Issue by grahamwills** [Brunel-Visualization/Brunel#28]
Our generation API makes a lot of assumptions about what we want. Instead we should have a much more configurable system. In particular:

 * Should the data be (i) referenced only (ii) sent down as summarized as possible (iii) sent down unaggregated
 * Should we generate build commands at the end, or leave that to the user
 * Do we want to expose hooks that will allow users to modify the Javascript objects
 * Readable Javascript, or minimal Javascript?

**Comment by fvanham** [comment]
Regarding data can I cast a vote for (ii). Trying to integrate this somewhere but I have the data already aggregated at the appropriate level using the appropriate aggregations and security settings, meaning it's quite small already. I can't possibly pass you the full unaggregated data since that'll be too big, and you'd be missing all the metadata and user access restrictions. Since the data itself is relatively small could I pass it in the data() function explicitly? E.g. instead of data(url:myfile), give you data(<csvstring>)

**Comment by danrope** [comment]
I've added a JS example that shows how to pass CSV data on a POST call to the service and render the resulting Javascript:  https://github.com/Brunel-Visualization/Brunel/blob/master/etc/src/main/resources/html/SampleJSApp.html
Note that this does use eval() and would likely have CORS issues if attempting to use the Bluemix service.  But perhaps this will be useful for demos.
