### ISSUE TITLE
all examples are broken, does not work in latest jupyter

### ISSUE THREAD

**Issue by antonkulaga** [Brunel-Visualization/Brunel#309]
All examples are broken on the website. 
It also tries to render javascript to jupyter cell that is prohibited by jupyter security rules:
```
%%brunel data('df') map x(State) color(Winter) tooltip(#all)
```
```
Uncaught (in promise) Error: Canceled
    at t.dispose (future.js:155)
    at default.js:384
    at Map.forEach (<anonymous>)
    at e.dispose (default.js:383)
    at e.dispose (default.js:244)
    at index.js:245
renderers.js:35 JupyterLab does not execute inline JavaScript in HTML output
u @ renderers.js:35

```

Regarding the version, I use latest https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook with jupyter-lab interface

**Comment by grahamwills** [comment]
Unfortunately, JupyterLab has broken away from the rest of the jupyter versions and has disabled the ability to have interactive visualizations. This has caused pretty much all the interactive JS libraries to fail in JupyterLab, but they do not seem interested in supporting this use case.

Their discussion boards suggest that it may be possible to customize your install not to be ban JS in webpages, so that's probably your best option.

**Comment by antonkulaga** [comment]
@grahamwills however, Brunel-Visualization does not use Jupyter lab but all examples there are totally broken, see https://github.com/Brunel-Visualization/Brunel/issues/310
