### ISSUE TITLE
Issue with Clustering Scala example notebook

### ISSUE THREAD

**Issue by svenhafeneger** [Brunel-Visualization/Brunel#75]
I tested the Clustering Scala notebook with IBM Analytics for Apache Spark (Scala 2.10, Spark 1.6.0).

The code with the brunel magic is not creating an output cell and no visualization is visible.

**Comment by joshisa** [comment]
@svenhafeneger 

I did some debugging and was able to get a visualization to show on an IBM Analytics for Apache Spark Scala Notebook.  

![brunelonbluemixspark](https://cloud.githubusercontent.com/assets/1133849/14908885/15da3008-0dab-11e6-84ae-3829d813f0a4.png)

Two things were required:

1.   Follow the guidance to Install found @ https://github.com/Brunel-Visualization/Brunel/tree/5b5f3ed3ccf30dad3b20f31c8803ed7416a9a78e/spark-kernel#install  (e.g.  %AddJar -magic http://www.brunelvis.org/jar/spark-kernel-brunel-all-1.1.jar )

2.   Because Bluemix runs in a SSL context, the css and script calls to http://www.brunelvis.org/ need to be under a SSL context as well.  If they are not, Google Chrome and most other browsers will block the mixed content calls.  To confirm, you can look within the javascript console of the browser when the notebook is loaded.

[WORKAROUND] I invoked the Chrome "--allow-running-insecure-content" flag and then attempted the brunel magic.  Worked like a charm.  For other browsers, you will need to follow their guidance for allowing mixed SSL when using Brunel within the IBM Analytics for Apache Spark notebooks.

It would be ideal if the hosted JS and CSS files referenced at www.brunelvis.org could be loaded either via SSL or NON-SSL to help resolve this issue.

**Comment by danrope** [comment]
Thanks!  And, agree--working on making brunelvis.org SSL.

**Comment by danrope** [comment]
We have enabled SSL and modified Brunel to use it by default.  A test .jar has been posted.  If anyone would like to confirm this is working, please try:

`%AddJar -magic https://brunelvis.org/jar/spark-kernel-brunel-all-1.2.jar `

Thx!
