### ISSUE TITLE
Reference lines

### ISSUE THREAD

**Issue by grahamwills** [Brunel-Visualization/Brunel#99]
for any chart it is often desirable to add reference lines. These should be as new elements and should have minimal and obvious syntax. If we assume  scatterplot of **summer** vs. **winter** temperatures, then the following should work:

 * `x(winter) y(summer) + line y(70)`  a horizontal line spanning the x values at y = 70
 * `x(winter) y(summer) + line x(70)`  a vertical line spanning the y values at x = 70
 * `x(winter) y(summer) + line mean(y)`  a horizontal line spanning the data at the man value of y

One question is whether the line is "infinite" -- does it always go end-to-end -- or does it span only the data. My preference would have it be infinite, and only span the data if you explicitly put in an x range, as the following:

 * `x(winter) y(summer) + line x(winter) range(winter) mean(y)`  a horizontal line spanning the data at the man value of y (the range(winter) just makes sure we have two endpoints; we don't absolutely need it)
  * `x(winter) y(summer) color(region) + line x(winter) range(winter) mean(y) color(region)` multiple reference lines for the data spanning the region's x ranges and at means for that subgroup

An open issue is how to make a diagonal reference line -- or maybe a general sloped line. Various workarounds occur to me, but it might be nice to think of a syntax that is general. Maybe we abuse the `fit` method?

**Comment by dpierucci** [comment]
Hi Graham,
Perhaps you know this already, but currently ...
x(winter) y(summer) + line y(70)  
does not work, but ...
x(winter) y(summer) + line x(winter) y(70) 
does work.
Thanks!

**Comment by danrope** [comment]
Looks good to me.  I suspect this approach would nearly if not immediately enable point references:  `x(70) y(70) point label("Point at 70,70")`

Regarding diagonals:  `fit(slope, intercept)` in conjunction with `range(x)` seems like it would accommodate nearly anything.  Perhaps`fit()` could just default to the very common case of `fit(1,0)`.  Also, I believe `y(70)` would yield the same results as `fit(0,70)` here--but possibly a difference in the implementation since there is no constant field in the latter.  

Question:  If the y-field is supplied to `range` instead of the x-field will this actually restrict the values over y or would it attempt to restrict over x using the min/max of y?  Wondering if there will be any issues lurking since the current `range` is a summary function of y across x.

**Comment by danrope** [comment]
It'd be nifty if this also supported summary functions that can produce 2 values & draw 2 lines:

`x(winter) y(summer) + line iqr(summer)`

[Related, a request to tweak `stddev` to return 2 values..]

Though, I suppose that thought winds up with something like this possible:

`x(winter) y(summer) + line range(summer) range(winter)`

2 horizontal lines, drawn at min/max of summer, but only over actual values of winter.

**Comment by grahamwills** [comment]
Added on develop branch

**Comment by dpierucci** [comment]
Would you please add tooltip support to the reference lines?

**Comment by grahamwills** [comment]
Support for tooltips and labels has been added. Note that you cannot use data fields in the tooltip -- just text -- as the guides do not have any data.
